[package]
name = "revmup-contract"
version = "0.1.0"
edition = "2021"


[dependencies]
ethers-core.workspace = true
ethers-contract.workspace = true
eyre.workspace = true
revm.workspace = true
hex.workspace = true

revmup-client = { path = "../revmup-client" }
