[package]
name = "revmup-contract"
version = "0.1.0"
edition = "2021"


[dependencies]
ethers-core = "2.0.8"
ethers-contract = "2.0.8"
eyre.workspace = true
revm.workspace = true
hex.workspace = true

revmup-client = { path = "../revmup-client" }
